site_name: My Personal Documentation

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Blog:
      - Post 1: server.md
      - Post 2: server.md
# theme:
#   name: readthedocs
# name: material
# palette:
#   - scheme: default
#     primary: indigo
#     accent: indigo
#     toggle:
#       icon: material/weather-night
#       name: Switch to dark mode
#   - scheme: slate
#     primary: indigo
#     accent: indigo
#     toggle:
#       icon: material/weather-sunny
#       name: Switch to light mode

site_url: ""
use_directory_urls: false
theme: material
plugins:
  - offline
  - search
  # - localsearch
